# Generated by Django 3.2.10 on 2022-07-10 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnityName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=255)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('entity', models.CharField(max_length=255)),
                ('activity_type', models.CharField(max_length=255)),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], default=1, max_length=255)),
                ('month', models.CharField(choices=[('1', 'Jan.'), ('2', 'Feb.'), ('3', 'Mar.'), ('4', 'Apr.'), ('5', 'May'), ('6', 'Jun.'), ('7', 'Jul.'), ('8', 'Aug.'), ('9', 'Sep.'), ('10', 'Oct.'), ('11', 'Nov.'), ('12', 'Dec.')], default=1, max_length=255)),
                ('periodicals', models.TextField(blank=True)),
                ('narations', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('target_date', models.DateField()),
                ('actual_completion_date', models.DateField()),
                ('event_modified', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('On_Time', 'On-Time'), ('Delayed', 'Delayed'), ('Pending', 'Pending')], default=1, max_length=255)),
                ('assign_to', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
