# Generated by Django 3.2.10 on 2022-07-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytracker',
            name='remakrs',
            field=models.TextField(blank=True),
        ),
    ]
