# Generated by Django 3.2.10 on 2022-07-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance_system', '0002_activitytracker_remakrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytracker',
            name='remakrs',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
