# Generated by Django 3.2.10 on 2022-07-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance_system', '0003_alter_activitytracker_remakrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytracker',
            name='status',
            field=models.CharField(default=1, editable=False, max_length=255),
        ),
    ]
