# Generated by Django 3.2.10 on 2022-07-13 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance_system', '0004_alter_activitytracker_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitytracker',
            old_name='actual_completion_date',
            new_name='actual_date',
        ),
        migrations.RenameField(
            model_name='activitytracker',
            old_name='remakrs',
            new_name='remarks',
        ),
    ]
