# Generated by Django 3.2.10 on 2022-07-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance_system', '0005_auto_20220713_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytracker',
            name='actual_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitytracker',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
