# Generated by Django 3.2.10 on 2022-07-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance_system', '0006_auto_20220713_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytracker',
            name='remarks',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
