# Generated by Django 3.2.10 on 2022-07-19 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance_system', '0008_alter_activitytracker_remarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityname',
            options={'verbose_name': 'ActivityName', 'verbose_name_plural': 'Activity Name'},
        ),
        migrations.AlterModelOptions(
            name='activitytracker',
            options={'verbose_name': 'ActivityTracker', 'verbose_name_plural': 'Activity Tracker Dashboard'},
        ),
        migrations.AlterModelOptions(
            name='activitytype',
            options={'verbose_name': 'ActivityType', 'verbose_name_plural': 'Activity Type'},
        ),
        migrations.AlterModelOptions(
            name='enityname',
            options={'verbose_name': 'EnityName', 'verbose_name_plural': 'Entity Name'},
        ),
        migrations.AlterField(
            model_name='activitytracker',
            name='activity_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Finance_system.activityname'),
        ),
        migrations.AlterField(
            model_name='activitytracker',
            name='activity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Finance_system.activitytype'),
        ),
        migrations.AlterField(
            model_name='activitytracker',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance_system.enityname'),
        ),
    ]
