# Generated by Django 3.2.10 on 2022-07-19 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance_system', '0009_auto_20220719_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytracker',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Finance_system.enityname'),
        ),
    ]
