# Generated by Django 3.2.10 on 2022-07-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance_system', '0010_alter_activitytracker_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytracker',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
