# Generated by Django 3.2.10 on 2022-08-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance_system', '0012_auto_20220808_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reporting_manager_email2',
        ),
    ]
