# Generated by Django 3.2.10 on 2022-08-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance_system', '0012_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
